eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: 'true'
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/
    fetch-registry: 'true'
charges:
  extraCharge: '0'
  platformFee: '230'
  deliveryCharge: '40'
  gstPercentage: '18'
spring:
  application:
    name: swigato-service
  datasource:
    password: ${POSTGRESDBPASSWORD}
    username: ${POSTGRESDBUSER}
    url: ${POSTGRESDBURL}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
server:
  port: '8088'
management:
  endpoints:
    web:
      exposure:
        include: '*'
swigato:
  host: host.docker.internal
  resturantPort: 7086
  customersPort: 7087

management:
  endpoints.web.exposure.include:
    - '*'
  endpoint.health.show-details: always
  health.circuitbreakers.enabled: true

resilience4j.circuitbreaker:
configs:
default:
    registerHealthIndicator: true
    slidingWindowSize: 10
    minimumNumberOfCalls: 5
    permittedNumberOfCallsInHalfOpenState: 3
    automaticTransitionFromOpenToHalfOpenEnabled: true
    waitDurationInOpenState: 5s
    failureRateThreshold: 50
    eventConsumerBufferSize: 10

