eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: 'true'
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/
    fetch-registry: 'true'
spring:
  application:
    name: returants-service
  datasource:
    password: ${POSTGRESDBPASSWORD}
    username: ${POSTGRESDBUSER}
    url: ${POSTGRESDBURL}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
server:
  port: '8086'
management:
  endpoints:
    web:
      exposure:
        include: '*'
