eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: 'true'
    service-url:
      defaultZone: http://localhost:8762/eureka/
    fetch-registry: 'true'
spring:
  application:
    name: resturants-service
  datasource:
    password: passpass
    username: admin
    url: jdbc:mysql://database001.c144wq06ejs8.eu-north-1.rds.amazonaws.com:3306/fo-resturants?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
server:
  port: '8086'
management:
  endpoints:
    web:
      exposure:
        include: '*'
