eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: 'true'
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: 'true'
spring:
  application:
    name: resturants-service
  datasource:
    password: pass
    username: postgres
    url: jdbc:postgresql://localhost:5435/fo-resturants
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
server:
  port: '8086'
management:
  endpoints:
    web:
      exposure:
        include: '*'
