eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: 'true'
    service-url:
      defaultZone: http://localhost:8762/eureka/
    fetch-registry: 'true'
charges:
  extraCharge: '0'
  platformFee: '3'
  deliveryCharge: '40'
  gstPercentage: '18'
spring:
  application:
    name: swigato-service
  datasource:
    url: jdbc:postgresql://localhost:5435/fo-swigato
    username: postgres
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
server:
  port: '8088'
logging:
  level:
    web: INFO
swigato:
  host: localhost
  resturantPort: 8086
  customersPort: 8087

management:
  endpoints.web.exposure.include:
    - '*'
  endpoint.health.show-details: always
  health.circuitbreakers.enabled: true

resilience4j.circuitbreaker:
configs:
default:
    registerHealthIndicator: true
    slidingWindowSize: 10
    minimumNumberOfCalls: 5
    permittedNumberOfCallsInHalfOpenState: 3
    automaticTransitionFromOpenToHalfOpenEnabled: true
    waitDurationInOpenState: 5s
    failureRateThreshold: 50
    eventConsumerBufferSize: 10
