server:
   port: ${PORT:5000}
      
spring:
     datasource:
       url: jdbc:postgresql://aws-postgres.c70owmmqe0r0.eu-north-1.rds.amazonaws.com:5432/DemoDB
       username: postgres
       password: postgres
     jpa:
       hibernate:
         ddl-auto: update
       show-sql: true
     cloud:
       aws:
         region:
           static: eu-north-1
         credentials:
           access-key: AKIAVHWHGB2PI6NUXLYV
           secret-key: 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

email:
  queueName: splitbill-emailQ
       
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://splitwiseeureka-env.eba-qp57xgcp.eu-north-1.elasticbeanstalk.com/eureka/
  instance:
    hostname: splitwiseeureka-env.eba-qp57xgcp.eu-north-1.elasticbeanstalk.com

resilience4j:
   retry:
      instances: 
         splitBillRT:
            max-attempts: 5
            wait-duration: 5s



external:
  api:
    sgroup:
      service:
        url: http://splitwise-group-env.eba-jpui4cbq.eu-north-1.elasticbeanstalk.com/


