server:
   port: ${PORT:5000}
      
spring:
     datasource:
       url: jdbc:postgresql://aws-postgres.c70owmmqe0r0.eu-north-1.rds.amazonaws.com:5432/DemoDB
       username: postgres
       password: postgres
     jpa:
       hibernate:
         ddl-auto: update
       show-sql: true
       
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://splitwiseeureka-env.eba-qp57xgcp.eu-north-1.elasticbeanstalk.com/eureka/
  instance:
    hostname: splitwiseeureka-env.eba-qp57xgcp.eu-north-1.elasticbeanstalk.com

external:
  api:
    suser:
      service:
        url: http://splitwise-users-env.eba-xig9a8iw.eu-north-1.elasticbeanstalk.com 

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always



resilience4j:
  circuitbreaker:
    instances:
      createGroupCB:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 150
        minimumNumberOfCalls: 15
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 16s
        permittedNumberOfCallsInHalfOpenState: 13
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        
  retry:
   instances:
      createGroupRetry:
         max-attempts: 12
         wait-duration: 15s
         
  
  ratelimiter:
    instances:
      createGroupRL:
        limit-refresh-period: 40s
        limit-for-period: 20
        timeout-duration: 20s
            
         



